jQuery(function($) {

    // This one is identical to the one in single_script.js
    // and group_script.js -- FIX
    function add_to_msg_box(node, prefix, msg) {
        var contents =
            "<div class=\"alert alert-danger alert-dismissible\" role=\"alert\">" +
            "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" " +
            "aria-label=\"Close\">" +
            "<span aria-hidden=\"true\">&times;</span>" +
            "</button>" +
            "<strong>" + prefix + "</strong>" + msg +

            "</div>";

        node.html(contents); // could be node.append...
    }

    // This event is generated by the 'bootstrap-select' addon to
    // bootstrap.
   $('#course-selector').on('loaded.bs.select', function() {
        $.ajax( DMindConfig.index_courses_url(), {
            dataType: "json", // expected back from server
            headers: {'X-Api-Key': DMindConfig.api_token() },
            method: 'GET',
            success: function(data, textStatus, jqXHR) {
                var html = '';
                for (var i = 0; i < data.length; i++) {
                    html += "<option value=\"" +
                        data[i].id + "\">" + data[i].name + "</option>";
                }
                $("#course-selector").append(html).selectpicker('refresh');
            },
        });
    });

    $('#course-selector').on('changed.bs.select', function(event) {
        $.ajax( DMindConfig.index_trainings_url(), {
            dataType: "json", // expected back from server
            headers: {'X-Api-Key': DMindConfig.api_token()},
            method: 'GET',
            data:  {course_id: $(event.target).val()},
            success: function(data, textStatus, jqXHR) {
                var html = '';
                for (var i = 0; i < data.length; i++) {
                    html += "<option value=\"" +
                        data[i].id + "\">" + data[i].city +
                        " " + data[i].start_date + " #" +
                        data[i].code + "</option>";
                }
                $("#training-selector").html(html).selectpicker('refresh');
            },
        });
    });

    $('#training-selector').on('changed.bs.select', function(event){
       $("#training-id").val($(event.target).val());
    });

    $('#course-selector').on('changed.bs.select', function(event){
        $("#course-id").val($(event.target).val());
    });

    $("#registration-type input").on('click', function(event){
        newval = $(this).val();
        $("#reg-type").val(newval);
    });

    $("#registration-user").submit(function(event) {
            var course = $("#course-id").val();
            var training = $("#training-id").val();

        if (course === "" || training === "") {
            event.preventDefault();
            add_to_msg_box($("#global-msg-box"),
                "Error:&nbsp;", "Please select both a course and a training.");
        }

    });


});
